# Generated by Django 4.2.7 on 2023-11-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_center.course')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=127)),
                ('accepted', models.BooleanField(default=False)),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='trade_center.project')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='trade_center.project')),
            ],
        ),
    ]
