# Generated by Django 4.2.7 on 2023-11-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switchproposal',
            old_name='contact_info',
            new_name='name',
        ),
        migrations.AddField(
            model_name='switchproposal',
            name='accepted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_center.switchproposal'),
        ),
    ]
