# Generated by Django 4.2.7 on 2023-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_center', '0002_rename_contact_info_switchproposal_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchproposal',
            name='accepted_by',
        ),
        migrations.AddField(
            model_name='switchproposal',
            name='accepted_by',
            field=models.ManyToManyField(to='trade_center.switchproposal'),
        ),
    ]
