# Generated by Django 4.2.7 on 2023-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_center', '0003_remove_switchproposal_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchproposal',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
